name: MobFS
on:
  workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run MobSF Analysis
        #uses: fundacaocerti/mobsf-action@v1.7.1
        uses: smk5797/mobsf-action@v1.7.15
        env:
          INPUT_FILE_NAME: apks/pivaa.apk
          SCAN_TYPE: apk
          OUTPUT_FILE_NAME: mobsf-report

      - name: Upload MobSF Analysis PDF Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.pdf
          path: mobsf-report.pdf

      - name: Upload MobSF Analysis JSON Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.json
          path: mobsf-report.json
