name: mobsfscan sarif report
on:
  workflow_dispatch

jobs:
  mobsfscan:
    runs-on: ubuntu-latest
    name: mobsfscan code scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: mobsfscan
      uses: MobSF/mobsfscan@main
      with:
        # scans only java code into app folder
        args: './app --sarif --output results.sarif || true'
    - name: Upload mobsfscan report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
        
    - name: mobsfscan-json
      uses: MobSF/mobsfscan@main
      with:
        # scans only java code into app folder
        args: './app --json --output results.json || true'        
    - name: Upload MobSF Analysis JSON Result
      uses: actions/upload-artifact@v2
      with:
        name: results.json
        path: results.json
